### PR TITLE
Migrate callbacks to promises for mongoose 7

### PR DESCRIPTION
**Pull request by amansingh63**
- Updated mongoose dependency to version 7.1.1
- Dependency versions Bump to latest
- Added prettier for code formatting
- eslint rules Updates
- Updated tests for promises

### CODE REVIEW

**Comment by LauchaSalinas** [comment]
Working for me, thanks for taking the time mate!

**Review by vkarpov15 — APPROVED** [review]
Thanks!

**Review by manojdm — APPROVED** [review]
Looks great :)

**Review by UzairAsadBaig — APPROVED** [review]

**Comment by ramiel** [comment]
@amansingh63 thanks for this PR. Can we get in contact to see if you want to became a maintainer of this library? I see some people is still using it and as I already said, I have no time to take care of it, but you did a good job here

**Comment by amansingh63** [comment]
@ramiel Yes, I'm definitely interested in discussing the possibility of becoming a maintainer for the library. Let's get in contact. Contact me on LinkedIn:  https://www.linkedin.com/in/amansingh63

**Pull request merged**
