### PR TITLE
Fix counterReset error when set  'start_seq'  to non-zero number

### PR DESCRIPTION
**Pull request by leeqiang**

### CODE REVIEW

**Comment by leeqiang** [comment]
@ramiel Please check this PR.

**Comment by ramiel** [comment]
Thank you, good catch!

**Comment by leeqiang** [comment]
@ramiel 😄, When are you publish a new version?

**Comment by ramiel** [comment]
Version 5.2.1 is out and contains this change!

**Comment by leeqiang** [comment]
@ramiel Thank you very much.

**Pull request merged**
